version: "2"
services:
  rethonk:
    image: rethinkdb
    volumes:
      - .:/data
  redis:
    image: redis
  andesite:
    image: natanbc/andesite
    environment:
      "andesite.transport.http.port": 5000
  mantaro:
    depends_on:
      - "rethonk"
      - "redis"
      - "andesite"
    image: mantaro/mantaro  
    volumes:
      - ./config-compose.json:/mantaro/config.json
  prometheus:
    depends_on:
      - "mantaro"
    image: prom/prometheus
    volumes:
      - ./prometheus:/prometheus-data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    depends_on:
      - "prometheus"
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
volumes:
  grafana-data: