version: "2"
services:
  rethonk:
    image: rethinkdb
    volumes:
      - .:/data
  redis:
    image: redis
  andesite:
    image: natanbc/andesite
    environment:
      "andesite.transport.http.port": 5000
  mantaro:
    depends_on:
      - "rethonk"
      - "redis"
      - "andesite"
    image: mantaro/mantaro
    volumes:
      - ./config-compose.json:/mantaro/config.json
  prometheus:
    depends_on:
      - "mantaro"
    image: prom/prometheus
    volumes:
      - ./prometheus:/prometheus-data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
